## Schmidt-Darstellung

Berechnung der Schmidt-Darstellung mit Hilfe von Qiskit und Standardbibliotheken von Python.

Berechnet werden die Koeffizienten und Basistransformationsmatrizen.

In [1]:
from sympy.physics.quantum import Dagger

from scipy import linalg
from math import sqrt

import numpy as np

np.set_printoptions(precision=5, suppress=True)

Definition des Zustands
$$
|\Psi\rangle = \frac{1}{2}( |00\rangle - |01\rangle + |10\rangle + |11\rangle )
$$
und dessen zugehörige Koeffizientenmatrix
$$
\begin{pmatrix}
1 & -1 \\ 1 & 1
\end{pmatrix}
$$

In [2]:
print("Zustand: (|00> - |01> + |10> + |11>)/2\n")
print("Koeffizientenmatrix" )
C = np.array([ [1.0, -1.0], 
               [1.0,  1.0]]
            )/2
print(C)

print("\nCheck: Summe der quadrierten Elemente")
print( np.sum(C**2) )

U, S, V_dag = linalg.svd(C,full_matrices=False)

print("\nMatrix U")
print(U)

print("\nDiagonalelemente der Matrix S")
print(S)

print("\nMatrix V_dag")
print(V_dag)

Zustand: (|00> - |01> + |10> + |11>)/2

Koeffizientenmatrix
[[ 0.5 -0.5]
 [ 0.5  0.5]]

Check: Summe der quadrierten Elemente
1.0

Matrix U
[[-0.70711 -0.70711]
 [-0.70711  0.70711]]

Diagonalelemente der Matrix S
[0.70711 0.70711]

Matrix V_dag
[[-1. -0.]
 [ 0.  1.]]


## Teilsystem 1

In [3]:
print("Basis-Vektoren Teilsystem 1")
print(U[:,0])
print(U[:,1])

Basis-Vektoren Teilsystem 1
[-0.70711 -0.70711]
[-0.70711  0.70711]


## Teilsystem 2

In [4]:
print("Basis-Vektoren Teilsystem 2")
# Zweimal adjungiert ergibt die Identität
# Es wird V benötigt und nich V_dag
# Alternative Extraktion der Vektoren (zeilenweise): V_dag[0,:], V_dag[1,:]
V = Dagger(V_dag) 
print(V[:,0])
print(V[:,1])

Basis-Vektoren Teilsystem 2
[-1. -0.]
[0. 1.]
