## Schmidt-Darstellung

Berechnung der Schmidt-Darstellung mit Hilfe von Qiskit und Standardbibliotheken von Python.

Berechnet werden die Koeffizienten und Basistransformationsmatrizen.

In [1]:
from sympy.physics.quantum import Dagger

from scipy import linalg
from math import sqrt

import numpy as np

np.set_printoptions(precision=5, suppress=True)

Definition des Zustands
$$
|\Psi\rangle = \frac{1}{\sqrt{3}}( |001\rangle + |010\rangle + |100\rangle )
$$
und dessen zugehörige Koeffizientenmatrix
$$
\frac{1}{\sqrt{3}} \begin{pmatrix}
0 & 1 \\ 1 & 0 
\end{pmatrix}
$$

In [2]:
print("Zustand: (|001> + |010> + |100> )/sqrt(3)\n")
print("Koeffizientenmatrix" )
C = np.array([ [0.0,  1.0], 
               [1.0,  0.0],
               [1.0,  0.0],
               [0.0,  0.0]]
            )/np.sqrt(3)


print(C)

U, S, V_dag = linalg.svd(C,full_matrices=False)

print("\nMatrix U")
print(U)

print("\nDiagonalelemente der Matrix S")
print(S)

print("\nMatrix V_dag")
print(V_dag)

Zustand: (|001> + |010> + |100> )/sqrt(3)

Koeffizientenmatrix
[[0.      0.57735]
 [0.57735 0.     ]
 [0.57735 0.     ]
 [0.      0.     ]]

Matrix U
[[ 0.       1.     ]
 [-0.70711  0.     ]
 [-0.70711  0.     ]
 [ 0.       0.     ]]

Diagonalelemente der Matrix S
[0.8165  0.57735]

Matrix V_dag
[[-1. -0.]
 [ 0.  1.]]


In [3]:
print("Basis-Vektoren Teilsystem 1")
print(U[:,0])
print(U[:,1])

Basis-Vektoren Teil 1
[ 0.      -0.70711 -0.70711  0.     ]
[1. 0. 0. 0.]


In [4]:
print("Basis-Vektoren Teilsystem 2")
V = Dagger(V_dag) 
print(V[:,0])
print(V[:,1])

Basis-Vektoren Teil 2
[-1. -0.]
[0. 1.]
